export { default as HomePage } from './HomePage'
export { default as CategoryPage } from './CategoryPage'
export { default as VendorStorePage } from './VendorStorePage'
export { default as ProductDetailPage } from './ProductDetailPage'
export { default as CartPage } from './CartPage'
export { default as CheckoutPage } from './CheckoutPage'
